# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c017e03a4a88a3f853386a095ba7c8fdfe84a59b2c29a7399f2409fb7df413136bcb80535e411077ceb14d81a680a8f8bd75290bd422f52ea2f5b4617c65a1f3

test:
  secret_key_base: d7f31b1f22989f2a102bf324b58200d893ae9b85e6ce6a647a0599e545e417ddb4f7912441872ad57ef391b10cbb15956a69b1c32f5fd67246e1fdd390d547cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
